## 🐍 numpy_fundamentals_project.py

In [1]:
import numpy as np
import time

### 1. Array creation, indexing, slicing


In [2]:
array_1d = np.array([10, 20, 30, 40, 50])
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

print("Indexing example:", array_1d[2])
print("Slicing example:", array_1d[1:4])


1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Indexing example: 30
Slicing example: [20 30 40]


### 2. Mathematical, axis-wise & statistical operations


In [3]:
print("Sum:", np.sum(array_2d))
print("Mean (axis=0):", np.mean(array_2d, axis=0))
print("Max:", np.max(array_2d))
print("Standard Deviation:", np.std(array_2d))


Sum: 45
Mean (axis=0): [4. 5. 6.]
Max: 9
Standard Deviation: 2.581988897471611


### 3. Reshaping and broadcasting


In [4]:
reshaped_array = array_1d.reshape(5, 1)
broadcasted_result = reshaped_array + np.array([1, 2, 3])

print("Reshaped Array:\n", reshaped_array)
print("Broadcasted Result:\n", broadcasted_result)


Reshaped Array:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Broadcasted Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]]


### 4. Save and load NumPy arrays


In [5]:
np.save("sample_array.npy", array_1d)
loaded_array = np.load("sample_array.npy")

print("Loaded Array from file:", loaded_array)


Loaded Array from file: [10 20 30 40 50]


### 5. Performance comparison: NumPy vs Python list


In [6]:
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

start = time.time()
python_list = [x * 2 for x in python_list]
python_time = time.time() - start

start = time.time()
numpy_array = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list execution time: {python_time:.4f} seconds")
print(f"NumPy array execution time: {numpy_time:.4f} seconds")


Python list execution time: 0.2773 seconds
NumPy array execution time: 0.0044 seconds
